cask_args appdir: '/Applications'
tap 'caskroom/cask'

brew 'mas'
brew 'zlib'
brew 'coreutils'
brew 'bash'
brew 'zsh'

brew 'curl'
brew 'git'
brew 'gist'
brew 'tree'
brew 'nvim'
#brew 'macvim'

brew 'colordiff'
brew 'ctags'
brew 'shellcheck'

# develop
cask 'google-chrome'
cask 'docker'
cask 'oni'
cask 'visual-studio-code'
cask 'paw'

# util
cask 'alfred'
cask 'keycastr'
cask 'duet'
cask 'station'

# communication
#cask 'discord' -> station
cask 'kindle'
cask 'qmk-toolbox'

#mas 'pocket', id: 568494494 -> station
#mas 'Slack', id: 803453959 -> station
